import {describe,it,expect,vi} from "vitest";
import {Dsh015CoreHost,LockedDsh015CoreExtension,assessDsh015CoreContract,dsh015CoreContractFingerprint,type Dsh015CoreContractObservation} from "../src/index.js";
const observation:Dsh015CoreContractObservation={platformVersion:"0.1.5-rc.2",sessionFormatVersion:3,packageVersions:Object.fromEntries(["session","session-persistence","session-format-catalog"].map(p=>[`@deepseek-ai/dsh-${p}`,"0.1.5-rc.2"])),implementationHashes:Object.fromEntries(["session","sessionPersistence","jsonlPersistence"].map(p=>[p,`sha256:${"a".repeat(64)}`])),methods:{sessionPersistence:["list","stat","open","create"],sessionHandle:["read","append","flush","close"],session:["validateStoredEvents"]}};
function fixture(){let live=false,exists=false,events:any[]=[],header:any={version:3,id:"synthetic",createdAt:0,delegationDepth:0,isSeeded:false},revision=0;const calls:string[]=[];let flushError=false;
 const handle=(access:string)=>({id:header.id,header,inheritedEventCount:0,access,read:async()=>{calls.push("read");return {events};},append:async(tail:any[])=>{calls.push("append");events.push(...tail);revision++;},flush:async()=>{calls.push("flush");if(flushError)throw new Error("fixture flush failure");},close:async()=>{calls.push("close");}});
 const host=new Dsh015CoreHost({persistence:{stat:async()=>exists?{header,revision}:undefined,list:async()=>[],open:async(_id,access)=>{calls.push(access);return handle(access) as any;},create:async h=>{calls.push("create");exists=true;header=h;return handle("write") as any;}},isSessionLive:()=>live,observation:async()=>observation,validateStoredEvents:(_h,e)=>{calls.push("validate");return e;},withOfflineSession:async(_id,action)=>{calls.push("offline");return action();},restoreOfflineSession:async snapshot=>{exists=snapshot.exists;events=snapshot.exists?[...snapshot.events]:[];if(snapshot.exists)header=snapshot.header;},metadata:{captureWorkspace:async()=>({workspaceId:null,memberIndex:null,beforeSessionId:null,archived:false}),captureProjection:async()=>({present:false}),captureRuntime:async()=>({coordinator:"cold",queryIndex:"synthetic"}),attachWorkspace:async()=>{},setArchive:async()=>{},invalidateProjection:async()=>{},reconcileRuntime:async()=>{},restoreWorkspace:async()=>{},restoreProjection:async()=>{}}});return {host,calls,header,setLive:(v:boolean)=>{live=v;},failFlush:()=>{flushError=true;}};}
describe("0.1.5 Core host handle boundary",()=>{
 it("probes exact implementation receipt and refuses old/mixed contracts",()=>{const pin=dsh015CoreContractFingerprint(observation);expect(assessDsh015CoreContract(observation,pin).status).toBe("compatible");expect(assessDsh015CoreContract({...observation,platformVersion:"0.1.1-rc.2"},pin).capabilities).toEqual([]);expect(assessDsh015CoreContract(observation,"unapproved").status).toBe("unsupported");});
 it("creates, appends, flushes then closes one offline owner and reads through a separate read handle",async()=>{const f=fixture();await f.host.createSessionWithEvents(f.header,[{type:"session/end-seed",seq:0,time:1,data:{}}],0);expect(f.calls).toEqual(["validate","create","append","flush","close"]);f.calls.length=0;expect(await f.host.captureSession("synthetic")).toMatchObject({exists:true,events:[{seq:0}]});expect(f.calls).toEqual(["read","read","validate","close"]);});
 it("never opens a second runtime writer and closes on flush failure",async()=>{const f=fixture();f.setLive(true);await expect(f.host.appendEvents("synthetic",[])).rejects.toThrow("DSH_BUSY");expect(f.calls).toEqual([]);f.setLive(false);f.failFlush();await expect(f.host.createSessionWithEvents(f.header,[],0)).rejects.toThrow("flush failure");expect(f.calls.at(-1)).toBe("close");});
 it("roundtrips a gateway snapshot through the offline admission barrier",async()=>{const f=fixture(),extension=new LockedDsh015CoreExtension(f.host,dsh015CoreContractFingerprint(observation));const before=await extension.capture({instanceId:"synthetic-instance",sessionId:"synthetic"});const state=await extension.apply({snapshot:before,header:f.header,events:[{type:"session/end-seed",seq:0,time:1,data:{}}]});expect(state.eventCount).toBe(1);expect(f.calls).toContain("offline");expect((await extension.restore({snapshot:before})).digest).toBe(before.before.digest);});
});
