import {describe,it,expect} from "vitest";
import {mkdtemp,mkdir,writeFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,dirname} from "node:path";
import {migrateLegacy} from "../src/legacy-import.js";
import {decodeGeneration,inspectV3NativeSpace} from "../src/generation-reader.js";
import {v3NativeSessionCodec} from "../src/native-session-codec.js";
import {normalizeV3Append} from "../src/normalize-append.js";
import {materializeV3,v3ProjectedNativeRevision} from "../src/materialize.js";
import {probeV3,REQUIRED_CAPABILITIES,REQUIRED_PACKAGES} from "../src/probe.js";
import {visibleContext,sessionFormatCatalog} from "../src/official.js";
import {recoverV3RuntimeTail} from "../src/runtime-tail-recovery.js";
const header={version:0,id:"synthetic-v3",createdAt:1,delegationDepth:0,isSeeded:false};
const raw=[{type:"turn/start",data:{turn:1}},{type:"step/start",data:{turn:1,step:1}},
 {type:"user/message",data:{id:"user-original",role:"user",source:{kind:"user"},content:[{type:"text",text:"hello"}]},surfaceOp:"append"},
 {type:"step/end",data:{turn:1,step:1}},{type:"turn/end",data:{turn:1,reason:{kind:"completed"}}}].map((e,seq)=>({...e,seq,time:seq+1}));
function artifact(events=raw){return {header,events,inheritedEventCount:0} as any;}
const at="2026-09-12T00:00:00.000Z";
const op=(events:any[],h:any)=>({runId:"synthetic-run",operationId:"synthetic-op",nativeSessionId:h.id,nativeRevision:events.length,observedAt:at,payload:{instanceId:"synthetic-instance",logicalSessionId:"synthetic-logical",header:h,inheritedEventCount:0,events}} as any);
async function project(events:any[]){const item={session:{id:"synthetic-logical",headVersionId:"synthetic-version",createdAt:at,updatedAt:at,title:"fixture",tags:[]},events,workspaceId:null,projectRoot:null};let payload:any;await materializeV3({run:{id:"synthetic-run",adapterId:"dsh-0.1.5",instanceId:"synthetic-instance",profileId:"web"},sessions:[item],workspaces:[]} as any,{writeWorkspace:async()=>{},writeSession:async(_id,p)=>{payload=p;}});return {item,payload};}
describe("fixed RC2 V3 backend",()=>{
 it("requires exact resolved packages and handle capabilities, not appendInformational",()=>{const environment={dshVersion:"0.1.5-rc.2",packageVersions:Object.fromEntries(REQUIRED_PACKAGES.map(p=>[p,"0.1.5-rc.2"])),runtimeCapabilities:[...REQUIRED_CAPABILITIES]};expect(probeV3(environment).status).toBe("verified");expect(probeV3({...environment,dshVersion:"0.1.5-rc.1"}).status).toBe("failed");expect(probeV3({...environment,packageVersions:{...environment.packageVersions,[REQUIRED_PACKAGES[0]]:"0.1.2-rc.1"}}).status).toBe("failed");expect(probeV3({...environment,runtimeCapabilities:[]}).capabilities).toEqual([]);});
 it("uses all official edges, inserts a system head, preserves message identity",()=>{const result=migrateLegacy(artifact());expect(result.artifact.header.version).toBe(3);expect(result.artifact.events.map(e=>e.type)).toContain("system/message");expect(result.artifact.events.find(e=>e.type==="user/message")!.data).toEqual(raw[2]!.data);expect(result.ledger.seqMap).toHaveLength(raw.length);expect(visibleContext(result.artifact)).toBeDefined();});
 it("archives an audited detail in place without changing the model surface",()=>{const events=[...raw.slice(0,3),{type:"dsh-runtime/detail",seq:3,time:4,data:{id:"execution",items:[],state:"completed"}},...raw.slice(3)].map((e,seq)=>({...e,seq}));const result=migrateLegacy(artifact(events as any));const card=result.artifact.events.find(e=>e.type==="dsh-runtime/detail")!;expect(card.ignorable).toBe(true);expect(result.ledger.informational[0]!.data).toEqual(events[3]!.data);expect(visibleContext(result.artifact)).toEqual(visibleContext(migrateLegacy(artifact()).artifact));expect(result.artifact.events[card.seq-1]!.type).toBe("user/message");});
 it("refuses unclassified and coordinate-bearing unknown events",()=>{expect(()=>migrateLegacy(artifact([{type:"future/semantic",seq:0,time:1,data:{},ignorable:true}] as any))).toThrow();expect(()=>migrateLegacy(artifact([{type:"dsh-runtime/detail",seq:0,time:1,data:{sourceSeq:2}}] as any))).toThrow(/converter/);});
 it("normalizes and materializes V3 twice with an exact revision prefix",async()=>{const converted=migrateLegacy(artifact()).artifact;const first=await project([...(await normalizeV3Append(op([...converted.events],converted.header))).events]);expect(first.payload.events).toEqual(converted.events);expect(v3ProjectedNativeRevision(first.item as any,first.payload)).toBe(converted.events.length);const second=await project([...(await normalizeV3Append(op(first.payload.events,first.payload.header))).events]);expect(second.payload.events).toEqual(first.payload.events);expect(()=>v3ProjectedNativeRevision(first.item as any,{...first.payload,events:[]})).toThrow(/prefix/);});
 it("rereads zstd, accepts only torn physical tails, selects V3 without fallback",async()=>{const root=await mkdtemp(join(tmpdir(),"dsh-maintenance-v3-fixture-"));try{const converted=migrateLegacy(artifact()).artifact;const payload={...converted,projectId:"synthetic"};const d=await v3NativeSessionCodec.describe(payload as any,root);const bytes=Buffer.from(v3NativeSessionCodec.encode(payload as any,d));expect(decodeGeneration(bytes,"zstd",3).artifact.events).toEqual(converted.events);const file=join(root,d.relativePath);await mkdir(dirname(file),{recursive:true});await writeFile(file,bytes);await writeFile(join(dirname(file),"session.jsonl"),"old-invalid\n");expect((await inspectV3NativeSpace(root))).toHaveLength(1);const plain=Buffer.from([sessionFormatCatalog.encodeCurrentHeader(converted.header,0),...converted.events.map(e=>sessionFormatCatalog.encodeCurrentEvent(e))].map(e=>JSON.stringify(e)+"\n").join(""));expect(decodeGeneration(Buffer.concat([plain,Buffer.from('{"partial":')]),"none",3).complete).toBe(false);expect(()=>decodeGeneration(Buffer.from(plain.toString().replace('"turn/start"','"future/required"')),"none",3)).toThrow();await writeFile(file,Buffer.from("corrupt"));await expect(inspectV3NativeSpace(root)).rejects.toThrow();}finally{await rm(root,{recursive:true,force:true});}});
});
